import { CustomButton } from "common/button.slint";
import { CustomRoundButton } from "common/round_button.slint";
import { BackLogItem, BackLogView } from "backlog.slint";
import { Colors } from "../styles/colors.slint";

export struct FigureItem {
    id: int,
    name: string,
    distance: string,
    body: image,
    face: image,
    rate: float,
    offset: float,
    face-x: float,
    face-y: float,
    base-x: float,
    base-y: float,
    x-offset: float,
    y-offset: float,
    width-ratio: float,
}

export component StoryView {
    in property <length> container-width;
    in property <length> container-height;
    in property <string> dialogue-1;
    in property <string> dialogue-2;
    in property <string> dialogue-3;
    in property <string> speaker;
    in property <[{ index: int, text: string }]> choose-branch;
    in property <[BackLogItem]> backlogs;
    in property <{ img: image, x_offset: float, y_offset: float, zoom: float }> bg;
    in property <[FigureItem]> figure-items;
    in property <int> current-choose: 0;
    in-out property <bool> is_backlog;
    in-out property <bool> is-auto;
    in-out property <bool> is-skip;

    in property <float> dialogue-opacity;
    in property <bool> is-bold;
    in property <bool> show-shadow;
    in property <string> dialogue-font;

    in-out property <bool> is-video: false;
    in property <image> video-frame;

    callback auto-play(bool);
    callback skip-play(bool);
    callback backlog();
    callback backlog-change(int);
    callback backlog-jump(string, int);
    callback backlog_replay(string, string);
    callback clicked();
    callback choose(string);
    callback settings();
    callback replay_voice();
    callback save-game();
    callback load-game();
    callback stop-video();

    TouchArea {
        width: parent.width;
        height: parent.height;

        scroll-event(event) => {
            if (root.is-video) {
                accept
            } else if (event.delta-y == 0) {
                accept
            } else if (event.delta-y > 0) {
                root.backlog();
                is_backlog = true;
                accept
            } else {
                reject
            }
        }
    }

    Rectangle {
        width: container-width;
        height: container-height;
        background: Colors.text-light;

        TouchArea {
            width: parent.width;
            height: parent.height;
            clicked => {
                if (root.is-video) {
                    root.stop-video();
                } else if (!is_backlog) {
                    root.clicked();
                }
            }
        }

        // 背景图片
        Image {
            source: bg.img;
            x: -self.width * bg.x-offset;
            y: -self.height * bg.y-offset;
            width: parent.width * bg.zoom;
            height: parent.height * bg.zoom;
        }

        // 角色立绘（动态数组渲染）
        for figure in figure-items: Image {
            source: figure.body;
            width: parent.width * figure.width-ratio;
            height: self.width / figure.rate;
            x: parent.width * figure.base-x + figure.x-offset * 1px;
            y: parent.height * figure.base-y + figure.y-offset * 1px - self.height * figure.offset;

            animate x, y {
                duration: 150ms;
                easing: ease-in-out;
            }

            // 角色表情
            Image {
                source: figure.face;
                width: self.source.width * parent.width / parent.source.width;
                height: self.source.height * parent.height / parent.source.height;
                x: parent.width * figure.face-x;
                y: parent.height * figure.face-y;
            }
        }

        // 对话框
        if root.current-choose == 0 && !root.is_backlog && !root.is-video: Rectangle {
            y: parent.height * 0.75;
            width: parent.width;
            height: parent.height * 0.25;
            background: rgba(0, 0, 0, dialogue-opacity);

            if root.show-shadow: Text {
                x: parent.width / 64 + parent.width / 1200;
                y: parent.width / 1200;
                text: root.speaker;
                font-size: parent.height * 2 / 15;
                font-weight: root.is-bold ? 700 : 400;
                font-family: root.dialogue-font;
                color: #00000066;
                wrap: word-wrap;
                width: parent.width * 31 / 32;
            }
            Text {
                text: root.speaker;
                x: parent.width / 64;
                y: 0;
                font-size: parent.height * 2 / 15;
                font-weight: root.is-bold ? 700 : 400;
                font-family: root.dialogue-font;
                color: Colors.text-light;
                wrap: word-wrap;
                width: parent.width * 31 / 32;
            }

            if root.show-shadow: Text {
                x: parent.width / 64 + parent.width / 1200;
                y: parent.height * 0.2 + parent.width / 1200;
                text: root.dialogue-1;
                font-size: parent.height * 2 / 15;
                font-weight: root.is-bold ? 700 : 400;
                font-family: root.dialogue-font;
                color: #00000066;
                wrap: word-wrap;
                width: parent.width * 31 / 32;
            }
            Text {
                text: root.dialogue-1;
                x: parent.width / 64;
                y: parent.height * 0.2;
                font-size: parent.height * 2 / 15;
                font-weight: root.is-bold ? 700 : 400;
                font-family: root.dialogue-font;
                color: Colors.text-light;
                wrap: word-wrap;
                width: parent.width * 31 / 32;
            }

            if root.show-shadow: Text {
                x: parent.width / 64 + parent.width / 1200;
                y: parent.height * 0.35 + parent.width / 1200;
                text: root.dialogue-2;
                font-size: parent.height * 2 / 15;
                font-weight: root.is-bold ? 700 : 400;
                font-family: root.dialogue-font;
                color: #00000066;
                wrap: word-wrap;
                width: parent.width * 31 / 32;
            }
            Text {
                text: root.dialogue-2;
                x: parent.width / 64;
                y: parent.height * 0.35;
                font-size: parent.height * 2 / 15;
                font-weight: root.is-bold ? 700 : 400;
                font-family: root.dialogue-font;
                color: Colors.text-light;
                wrap: word-wrap;
                width: parent.width * 31 / 32;
            }

            if root.show-shadow: Text {
                x: parent.width / 64 + parent.width / 1200;
                y: parent.height * 0.5 + parent.width / 1200;
                text: root.dialogue-3;
                font-size: parent.height * 2 / 15;
                font-weight: root.is-bold ? 700 : 400;
                font-family: root.dialogue-font;
                color: #00000066;
                wrap: word-wrap;
                width: parent.width * 31 / 32;
            }
            Text {
                text: root.dialogue-3;
                x: parent.width / 64;
                y: parent.height * 0.5;
                font-size: parent.height * 2 / 15;
                font-weight: root.is-bold ? 700 : 400;
                font-family: root.dialogue-font;
                color: Colors.text-light;
                wrap: word-wrap;
                width: parent.width * 31 / 32;
            }
        }

        // 选择分支
        if root.current-choose != 0 && !root.is_backlog && !root.is-video: Rectangle {
            height: parent.height * 0.05 * (2 * root.current-choose - 1);
            width: parent.width * 0.75;

            for choose in root.choose-branch: Rectangle {
                height: parent.height / (2 * root.current-choose - 1);
                y: 2 * (choose.index - 1) * parent.height / (2 * root.current-choose - 1);
                background: Colors.overlay-background;

                Text {
                    text: choose.text;
                    font-size: parent.height;
                    color: Colors.text-light;
                }

                TouchArea {
                    clicked => { root.choose(choose.text); }
                }
            }
        }

        //下方按钮
        if !root.is_backlog && !root.is-video: Rectangle {
            width: parent.width;
            height: parent.width * 0.04;
            y: parent.height - self.height - parent.height * 0.02;

            CustomRoundButton {
                width: parent.height;
                height: parent.height;
                x: parent.width * 0.61 - self.width;
                y: 0;
                text: "语音";
                clicked => { root.replay-voice(); }
            }

            CustomRoundButton {
                width: parent.height;
                height: parent.height;
                x: parent.width * 0.67 - self.width;
                y: 0;
                text: "存档";
                clicked => { root.save-game(); }
            }

            CustomRoundButton {
                width: parent.height;
                height: parent.height;
                x: parent.width * 0.73 - self.width;
                y: 0;
                text: "读档";
                clicked => { root.load-game(); }
            }

            CustomRoundButton {
                width: parent.height;
                height: parent.height;
                x: parent.width * 0.79 - self.width;
                y: 0;
                text: "自动";
                is-on: is-auto;
                clicked => {
                    is-auto = !is-auto;
                    is-skip = false;
                    root.auto-play(true);
                }
            }

            CustomRoundButton {
                width: parent.height;
                height: parent.height;
                x: parent.width * 0.85 - self.width;
                y: 0;
                text: "快进";
                is-on: is-skip;
                clicked => {
                    is-skip = !is-skip;
                    is-auto = false;
                    root.skip-play(true);
                }
            }

            CustomRoundButton {
                width: parent.height;
                height: parent.height;
                x: parent.width * 0.91 - self.width;
                y: 0;
                text: "履历";
                clicked => {
                    is-backlog = !is-backlog;
                    is-auto = false;
                    is-skip = false;
                    root.backlog();
                }
            }

            CustomRoundButton {
                width: parent.height;
                height: parent.height;
                x: parent.width * 0.97 - self.width;
                y: 0;
                text: "设置";
                clicked => { root.settings(); }
            }
        }

        //历史记录
        if root.is_backlog && !root.is-video: BackLogView {
            container-width: parent.width;
            container-height: parent.height;
            is-bold: root.is-bold;
            dialogue-font: root.dialogue-font;
            backlogs <=> root.backlogs;
            back => { is_backlog = false; }
            backlog-change(i) => { root.backlog-change(i); }
            backlog-jump(s, i) => { root.backlog-jump(s, i); }
            backlog-replay(n, v) => { root.backlog-replay(n, v) }
        }

        // 视频层（最上层）
        if root.is-video: Rectangle {
            width: parent.width;
            height: parent.height;
            background: #000000;

            Image {
                source: root.video-frame;
                width: parent.width;
                height: parent.height;
                image-fit: contain;
            }
        }
    }
}