import { CustomButton } from "common/button.slint";
import { CustomRoundButton } from "common/round_button.slint";
import { Video } from "common/video.slint";
import { BackLogView } from "backlog.slint";
import { Colors } from "../styles/colors.slint";

export component StoryView {
    in property <length> container-width;
    in property <length> container-height;
    in property <string> dialogue-1;
    in property <string> dialogue-2;
    in property <string> dialogue-3;
    in property <string> speaker;
    in property <[{ index: int, text: string }]> choose-branch;
    in property <[{ front: string, back: string, script: string, index: int }]> backlogs;
    in property <{ img: image, x_offset: float, y_offset: float, zoom: float }> bg;
    in property <{ body: image, rate: float, offset: float }> fg-no-0;
    in property <{ face: image, face-x: float, face-y: float }> face-no-0;
    in property <{ body: image, rate: float, offset: float }> fg-z1-0;
    in property <{ face: image, face-x: float, face-y: float }> face-z1-0;
    in property <{ x_offset: length, y_offset: length }> offset-z1-0;
    in property <{ body: image, rate: float, offset: float }> fg-z1-1;
    in property <{ face: image, face-x: float, face-y: float }> face-z1-1;
    in property <{ x_offset: length, y_offset: length }> offset-z1-1;
    in property <{ body: image, rate: float, offset: float }> fg-z1--1;
    in property <{ face: image, face-x: float, face-y: float }> face-z1--1;
    in property <{ x_offset: length, y_offset: length }> offset-z1--1;
    in property <{ body: image, rate: float, offset: float }> fg-z1-2;
    in property <{ face: image, face-x: float, face-y: float }> face-z1-2;
    in property <{ x_offset: length, y_offset: length }> offset-z1-2;
    in property <{ body: image, rate: float, offset: float }> fg-z1--2;
    in property <{ face: image, face-x: float, face-y: float }> face-z1--2;
    in property <{ x_offset: length, y_offset: length }> offset-z1--2;
    in property <image> video-frame;
    in property <int> current-choose: 0;
    in-out property <bool> is_backlog;
    in-out property <bool> is-auto;
    in-out property <bool> is-skip;
    in-out property <bool> is-video;
    in property <float> dialogue-opacity;

    callback auto-play(bool);
    callback skip-play(bool);
    callback backlog();
    callback backlog-change(int);
    callback backlog-jump(string, int);
    callback clicked();
    callback choose(string);
    callback stop-video();
    callback settings();
    callback save-game();
    callback load-game();

    if !is-video: TouchArea {
        width: parent.width;
        height: parent.height;

        scroll-event(event) => {
            if (event.delta-y > 0) {
                root.backlog();
                is_backlog = true;
                accept
            } else {
                reject
            }
        }
    }

    if is-video: Video {
        width: parent.width;
        height: parent.height;
        video_frame: root.video-frame;
        clicked => { root.stop-video() }
    }

    Rectangle {
        width: container-width;
        height: container-height;
        background: Colors.text-light;

        TouchArea {
            width: parent.width;
            height: parent.height;
            clicked => { if (!is_backlog) {root.clicked();} }
        }

        // 背景图片
        Image {
            source: bg.img;
            x: -self.width * bg.x-offset;
            y: -self.height * bg.y-offset;
            width: parent.width * bg.zoom;
            height: parent.height * bg.zoom;
        }

        // 角色立绘 居中远距离
        Image {
            source: fg-no-0.body;
            width: parent.width * 0.25;
            height: self.width / fg-no-0.rate;
            x: parent.width * 0.375;
            y: parent.height / 6 - self.height * fg-no-0.offset;

            // 角色表情
            Image {
                source: face-no-0.face;
                width: self.source.width * parent.width / parent.source.width;
                height: self.source.height * parent.height / parent.source.height;
                x: parent.width * face-no-0.face-x;
                y: parent.height * face-no-0.face-y;
            }
        }
        
        // 角色立绘 居中近距离
        Image {
            in-out property <length> x-offset: offset-z1-0.x-offset;
            in-out property <length> y-offset: offset-z1-0.y-offset;

            animate x-offset, y-offset {
                 duration: 150ms;
                 easing: ease-in-out;
            }
        
            source: fg-z1-0.body;
            width: parent.width * 0.34;
            height: self.width / fg-z1-0.rate;
            x: parent.width * 0.33 + x-offset;
            y: parent.height / 8 + y-offset - self.height * fg-z1-0.offset;

            // 角色表情
            Image {
                source: face-z1-0.face;
                width: self.source.width * parent.width / parent.source.width;
                height: self.source.height * parent.height / parent.source.height;
                x: parent.width * face-z1-0.face-x;
                y: parent.height * face-z1-0.face-y;
            }
        }

        // 角色立绘 左侧面近距离
        Image {
            in-out property <length> x-offset: offset-z1--1.x-offset;
            in-out property <length> y-offset: offset-z1--1.y-offset;

            animate x-offset, y-offset {
                 duration: 150ms;
                 easing: ease-in-out;
            }

            source: fg-z1--1.body;
            width: parent.width * 0.34;
            height: self.width / fg-z1--1.rate;
            x: x-offset;
            y: parent.height / 8 + y-offset - self.height * fg-z1--1.offset;

            // 角色表情
            Image {
                source: face-z1--1.face;
                width: self.source.width * parent.width / parent.source.width;
                height: self.source.height * parent.height / parent.source.height;
                x: parent.width * face-z1--1.face-x;
                y: parent.height * face-z1--1.face-y;
            }
        }

        // 角色立绘 右侧面近距离
        Image {
            in-out property <length> x-offset: offset-z1-1.x-offset;
            in-out property <length> y-offset: offset-z1-1.y-offset;

            animate x-offset, y-offset {
                 duration: 150ms;
                 easing: ease-in-out;
            }

            source: fg-z1-1.body;
            width: parent.width * 0.34;
            height: self.width / fg-z1-1.rate;
            x: parent.width * 0.66 + x-offset;
            y: parent.height / 8 + y-offset - self.height * fg-z1-1.offset;

            // 角色表情
            Image {
                source: face-z1-1.face;
                width: self.source.width * parent.width / parent.source.width;
                height: self.source.height * parent.height / parent.source.height;
                x: parent.width * face-z1-1.face-x;
                y: parent.height * face-z1-1.face-y;
            }
        }

        // 角色立绘 双人位左侧面近距离
        Image {
            in-out property <length> x-offset: offset-z1--2.x-offset;
            in-out property <length> y-offset: offset-z1--2.y-offset;

            animate x-offset, y-offset {
                 duration: 150ms;
                 easing: ease-in-out;
            }
        
            source: fg-z1--2.body;
            width: parent.width * 0.34;
            height: self.width / fg-z1--2.rate;
            x: parent.width * 0.16 + x-offset;
            y: parent.height / 8 + y-offset - self.height * fg-z1--2.offset;

            // 角色表情
            Image {
                source: face-z1--2.face;
                width: self.source.width * parent.width / parent.source.width;
                height: self.source.height * parent.height / parent.source.height;
                x: parent.width * face-z1--2.face-x;
                y: parent.height * face-z1--2.face-y;
            }
        }

        // 角色立绘 双人位右侧面近距离
        Image {
            in-out property <length> x-offset: offset-z1-2.x-offset;
            in-out property <length> y-offset: offset-z1-2.y-offset;

            animate x-offset, y-offset {
                 duration: 150ms;
                 easing: ease-in-out;
            }
        
            source: fg-z1-2.body;
            width: parent.width * 0.34;
            height: self.width / fg-z1-2.rate;
            x: parent.width * 0.5 + x-offset;
            y: parent.height / 8 + y-offset - self.height * fg-z1-2.offset;

            // 角色表情
            Image {
                source: face-z1-2.face;
                width: self.source.width * parent.width / parent.source.width;
                height: self.source.height * parent.height / parent.source.height;
                x: parent.width * face-z1-2.face-x;
                y: parent.height * face-z1-2.face-y;
            }
        }

        // 对话框
        if root.current-choose == 0 && !root.is_backlog: Rectangle {
            y: parent.height * 0.75;
            width: parent.width;
            height: parent.height * 0.25;
            background: rgba(0, 0, 0, dialogue-opacity);

            Text {
                text: root.speaker;
                x: parent.width / 64;
                y: 0;
                font-size: parent.height * 2 / 15;
                color: Colors.text-light;
                wrap: word-wrap;
                width: parent.width * 31 / 32;
            }

            Text {
                text: root.dialogue-1;
                x: parent.width / 64;
                y: parent.height * 0.2;
                font-size: parent.height * 2 / 15;
                color: Colors.text-light;
                wrap: word-wrap;
                width: parent.width * 31 / 32;
            }
            
            Text {
                text: root.dialogue-2;
                x: parent.width / 64;
                y: parent.height * 0.35;
                font-size: parent.height * 2 / 15;
                color: Colors.text-light;
                wrap: word-wrap;
                width: parent.width * 31 / 32;
            }
            
            Text {
                text: root.dialogue-3;
                x: parent.width / 64;
                y: parent.height * 0.5;
                font-size: parent.height * 2 / 15;
                color: Colors.text-light;
                wrap: word-wrap;
                width: parent.width * 31 / 32;
            }
        }

        // 选择分支
        if root.current-choose != 0 && !root.is_backlog: Rectangle {
            height: parent.height * 0.05 * (2 * root.current-choose - 1);
            width: parent.width * 0.75;

            for choose in root.choose-branch: Rectangle {
                height: parent.height / (2 * root.current-choose - 1);
                y: 2 * (choose.index - 1) * parent.height / (2 * root.current-choose - 1);
                background: Colors.overlay-background;

                Text {
                    text: choose.text;
                    font-size: parent.height;
                    color: Colors.text-light;
                }

                TouchArea {
                    clicked => { root.choose(choose.text); }
                }
            }
        }

        //下方按钮
        if !root.is_backlog: Rectangle {
            width: parent.width;
            height: parent.width * 0.04;
            y: parent.height - self.height - parent.height * 0.02;

            CustomRoundButton {
                width: parent.height;
                height: parent.height;
                x: parent.width * 0.73 - self.width;
                y: 0;
                text: "存档";
                clicked => { root.save-game(); }
            }

            CustomRoundButton {
                width: parent.height;
                height: parent.height;
                x: parent.width * 0.79 - self.width;
                y: 0;
                text: "读档";
                clicked => { root.load-game(); }
            }

            CustomRoundButton {
                width: parent.height;
                height: parent.height;
                x: parent.width * 0.85 - self.width;
                y: 0;
                text: "自动";
                is-on: is-auto;
                clicked => {
                    is-auto = !is-auto;
                    root.auto-play(true);
                }
            }

            CustomRoundButton {
                width: parent.height;
                height: parent.height;
                x: parent.width * 0.91 - self.width;
                y: 0;
                text: "快进";
                is-on: is-skip;
                clicked => {
                    is-skip = !is-skip;
                    root.skip-play(true);
                }
            }

            CustomRoundButton {
                width: parent.height;
                height: parent.height;
                x: parent.width * 0.97 - self.width;
                y: 0;
                text: "设置";
                clicked => { root.settings(); }
            }
        }

        //历史记录
        if root.is_backlog: BackLogView {
            container-width: parent.width;
            container-height: parent.height;
            backlogs <=> root.backlogs;
            back => { is_backlog = false; }
            backlog-change(i) => { root.backlog-change(i); }
            backlog-jump(s, i) => { root.backlog-jump(s, i); }
        }
    }
}