[initialize]
script_path = "./source/script/"
background_path = "./source/background/"
cg_path = "./source/cg/"
voice_path = "./source/voice/"
bgm_path = "./source/bgm/"
video_path =  "./source/video/"
figure_path = "./source/figure/"
save_path = "./savedata/"

[character]
list = ["rir", "rar"]
